labels:
  - name: license:spdx-noncompliant
    color: FF0000
    description: "Files changed in PR are missing SPDX headers or copyright lines"
  - name: license:spdx-fixed
    color: 0E8A16
    description: "SPDX issues fixed"